//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsrivaMobileWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esrivamobileEntities : DbContext
    {
        public esrivamobileEntities()
            : base("name=esrivamobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnetrole> aspnetroles { get; set; }
        public virtual DbSet<aspnetuserclaim> aspnetuserclaims { get; set; }
        public virtual DbSet<aspnetuserlogin> aspnetuserlogins { get; set; }
        public virtual DbSet<aspnetuser> aspnetusers { get; set; }
        public virtual DbSet<dbfollower> dbfollowers { get; set; }
        public virtual DbSet<dbfollowing> dbfollowings { get; set; }
        public virtual DbSet<dbfriendlist> dbfriendlists { get; set; }
        public virtual DbSet<dbnotification> dbnotifications { get; set; }
        public virtual DbSet<dbpodcast> dbpodcasts { get; set; }
        public virtual DbSet<dbuser> dbusers { get; set; }
    }
}
